version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: example
      DB_NAME: restaurantdb
    volumes:
      - ./restaurantDB.txt:/var/www/html/restaurantDB.txt
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: restaurantdb
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge