name: Build, Test, and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout code
        uses: actions/checkout@v2

     
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/restaurant-project:latest .

      
      - name: Tag Docker image
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/restaurant-project:latest ${{ secrets.DOCKER_USERNAME }}/restaurant-project:${{ github.sha }}

      
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/restaurant-project:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/restaurant-project:${{ github.sha }}

      
      # - name: Deploy to Server
      #   env:
      #     SERVER_IP: ${{ secrets.SERVER_IP }}
      #     SERVER_USER: ${{ secrets.SERVER_USER }}
      #     SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      #   run: |
      #     sshpass -p $SERVER_PASSWORD ssh $SERVER_USER@$SERVER_IP "
      #     docker pull ${{ secrets.DOCKER_USERNAME }}/restaurant-project:latest &&
      #     docker stop restaurant-app || true &&
      #     docker rm restaurant-app || true &&
      #     docker run -d --name restaurant-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/restaurant-project:latest"
